### ISSUE TITLE
Comparison with the Percolate package

### ISSUE THREAD

**Issue by dandv** [smowden/meteor-intercom#1]
I was [searching Atmosphere for Intercom](https://atmospherejs.com/?q=intercom) and found a bunch of packages.

How is this one, https://atmospherejs.com/smowden/intercom different from https://atmospherejs.com/percolate/intercom? The README looks identical.

If this was a test and/or you no longer need the package to be searchable on Atmosphere, the package can be hidden from searches. It will still remain usable by dependent apps and packages.

```
meteor admin set-unmigrated smowden:intercom
```

This will help us have a clean atmosphere!

**Comment by smowden** [comment]
thanks I'll do that, at one point there was a bug I had to fix to get Intercom to work, but I believe that was fixed by Intercom in the meantime.
